# Generated by Django 3.2.2 on 2021-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('prise', models.IntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('user_id', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('price_all', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
