# Generated by Django 3.2.2 on 2021-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('prise', models.IntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='prise',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_product',
            field=models.ManyToManyField(to='catalog.Orders_product'),
        ),
    ]
