# Generated by Django 3.2.2 on 2021-05-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210511_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orders_product',
        ),
        migrations.AddField(
            model_name='orders_product',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.orders'),
            preserve_default=False,
        ),
    ]
